[features]
seeds = false
skip-lint = false
[programs.testnet]
hackathon = "6HzSgqLgUCFKSs48EPMWtuE5GznKTqMJQPxNMnqHNC41"
[programs.devnet]
hackathon = "6HzSgqLgUCFKSs48EPMWtuE5GznKTqMJQPxNMnqHNC41"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/chung/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
